services:
  - type: web
    name: good-conduct-training
    runtime: node
    plan: free
    buildCommand: pnpm install --frozen-lockfile && pnpm run build
    startCommand: pnpm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SITE_PASSWORD
        sync: false
      - key: SITE_SESSION_SECRET
        generateValue: true
